version: '2'

services:
    app:
        build:
            context: docker/apache-php
            dockerfile: Dockerfile
            args:
                PUID: ${UID}
                PGID: ${GID}
        container_name: "${CLIENT_NAME}.${PROJECT_NAME}"
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./:/var/www/localhost
        links:
            - mysql
        restart: always
        environment:
            HTTP_PORT: 8000

    mysql:
        build:
            context: docker/mysql
            dockerfile: Dockerfile
            args:
                PUID: ${UID}
        container_name: "${CLIENT_NAME}.${PROJECT_NAME}.mysql"
        user: "${UID}:${GID}"
        volumes:
            - ./var/mysql:/var/lib/mysql
            - ./tmp:/tmp/host
        ports:
            - "${MYSQL_PORT}:3306"
        expose:
            - "${MYSQL_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: ${PROJECT_NAME}
            MYSQL_USER: ${PROJECT_NAME}
            MYSQL_PASSWORD: 123456
            MYSQL_PORT: ${MYSQL_PORT}
        restart: always
